apiVersion: v1
kind: Pod
metadata:
  name: cve-pocketbase
spec:
  containers:
    - image: cve_pocketbase
      name: cve-pocketbase
      ports:
        - containerPort: 8090
          name: http
          protocol: TCP
      imagePullPolicy: Never