apiVersion: v1
kind: Pod
metadata:
  name: cve-t3
spec:
  containers:
    - image: cve_t3
      name: cve-t3
      ports:
        - containerPort: 3000
          name: http
          protocol: TCP
      imagePullPolicy: Never
      livenessProbe:
        httpGet:
          path: /
          port: 3000
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3