apiVersion: v1
kind: Pod
metadata:
  name: cve-cve
spec:
  containers:
    - image: cve_cve
      name: cve-cve
      ports:
        - containerPort: 50052
          name: grpc
          protocol: TCP
      imagePullPolicy: Never
      livenessProbe:
        tcpSocket:
          port: 50052
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3