apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - extraPortMappings:
    - containerPort: 30000
      hostPort: 8080
    - containerPort: 30001
      hostPort: 9001
    - containerPort: 30002
      hostPort: 9002
    - containerPort: 30003
      hostPort: 9003
    - containerPort: 30004
      hostPort: 9004